# https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-deployment-guide
# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    type: LoadBalancer

global:
  enabled: true
  name: consul
  datacenter: azure-dev
  peering:
    enabled: true
  tls:
    enabled: true
  acls:
    manageSystemACLs: true

server:
  enabled: true
  # The number of server agents to run. This determines the fault tolerance of the cluster.
  replicas: 1

connectInject:
  enabled: true
  default: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer

# Reach Other DC
meshGateway:
  enabled: true